import { afterEach, expect, it, vi } from 'vitest';
import { PollingManager } from '../src/polling.js';
afterEach(() => vi.useRealTimers());
it('continues polling after 10 unexpected failures and recovers', async () => {
  vi.useFakeTimers();
  const poll = vi.fn().mockRejectedValue(new Error('Temporary failure'));
  const manager = new PollingManager(poll, {intervalMs: 1000, maxBackoffMs: 1000});
  manager.start();
  await vi.advanceTimersByTimeAsync(12_000);
  expect(poll.mock.calls.length).toBeGreaterThan(10);
  poll.mockResolvedValue(undefined);
  const before = poll.mock.calls.length;
  await vi.advanceTimersByTimeAsync(1000);
  expect(poll).toHaveBeenCalledTimes(before + 1);
  await manager.stop();
});
it('runs immediately on request and replaces the pending timer', async () => {
  vi.useFakeTimers();
  const poll = vi.fn().mockResolvedValue(undefined);
  const manager = new PollingManager(poll, {intervalMs: 900_000});
  manager.start();
  await vi.advanceTimersByTimeAsync(1000);
  manager.requestPoll();
  await vi.advanceTimersByTimeAsync(0);
  expect(poll).toHaveBeenCalledTimes(2);
  expect(manager.getStatus().nextPoll).not.toBeNull();
  await vi.advanceTimersByTimeAsync(899_000);
  expect(poll).toHaveBeenCalledTimes(2);
  await vi.advanceTimersByTimeAsync(1000);
  expect(poll).toHaveBeenCalledTimes(3);
  await manager.stop();
});
it('queues one fresh scan after settings change during a scan without overlap', async () => {
  vi.useFakeTimers();
  let release!: () => void;
  const poll = vi.fn().mockImplementationOnce(() => new Promise<void>(resolve => { release = resolve; })).mockResolvedValue(undefined);
  const manager = new PollingManager(poll, {intervalMs: 30_000});
  manager.start();
  manager.requestPoll(); manager.requestPoll();
  expect(poll).toHaveBeenCalledTimes(1);
  expect(manager.getStatus().inProgress).toBe(true);
  release();
  await vi.advanceTimersByTimeAsync(0);
  expect(poll).toHaveBeenCalledTimes(2);
  await manager.stop();
  await vi.advanceTimersByTimeAsync(60_000);
  expect(poll).toHaveBeenCalledTimes(2);
  expect(manager.getStatus()).toEqual({running: false, inProgress: false, nextPoll: null});
});
